package common

const (
	MsgInitialization       = "initialization"
	MsgPrecedingsEuresult   = "precedingsEuresult"
	MsgSelectedReceiptsHash = "selectedReceiptsHash"
	MsgSelectedReceipts     = "selectedReceipts"

	MsgAccessRecordSelected  = "accessRecordSelected"
	MsgEuResults             = "euResults"
	MsgGenerationReapingList = "generationReapingList"

	MsgBlockEnd        = "blockend"
	MsgReceipts        = "receipts"
	MsgInclusive       = "inclusive"
	MsgBlockCompleted  = "blockCompleted"
	MsgReceiptHashList = "receiptHashList"

	MsgArbitrateReapinglist  = "arbitratereapinglist"
	MsgPreProcessedEuResults = "preProcessedEuResults"

	MsgTxAccessRecords             = "txAccessRecords"
	MsgPreProcessedImportEuResults = "preProcessedImportEuResults"
	MsgUrlUpdate                   = "urlupdate"
	MsgObjectCached                = "objectCached"
	MsgApcHandleInit               = "apchandleInit"
	MsgCached                      = "cached"
	MsgTransactionalAddCompleted   = "transactionalAddCompleted"
	MsgGc                          = "gc"
	MsgAcctHash                    = "accthash"
	MsgExecuted                    = "executed"
	MsgGenerationReapingCompleted  = "generationReapingCompleted"
	MsgApcHandle                   = "apchandle"
	MsgGeneralDB                   = "generalDB"
	MsgGeneralCompleted            = "generalCompleted"
	MsgGeneralPrecommit            = "generalPrecommit"
	MsgGeneralCommit               = "generalCommit"
	MsgExtAppHash                  = "external.apphash"
	MsgMetaBlock                   = "metablock"
	MsgTxLocals                    = "txLocals"
	MsgAppHash                     = "appHash"
	MsgExtReapCommand              = "external.reapcommand"
	MsgExtTxBlocks                 = "external.txblocks"
	MsgExtBlockCompleted           = "external.blockcompleted"
	MsgExtReapingList              = "external.reapinglist"
	MsgExtBlockStart               = "external.blockstart"
	MsgConsensusMaxPeerHeight      = "consensus.maxpeerheight"
	MsgConsensusUp                 = "consensus.up"
	MsgExtBlockEnd                 = "external.blockend"
	MsgBlockStart                  = "blockstart"
	MsgStateSyncDone               = "statesync.done"
	MsgReapCommand                 = "reapCommand"
	MsgTxBlocks                    = "txBlocks"
	MsgReapinglist                 = "reapinglist"
	MsgStateSyncStart              = "statesync.start"
	MsgSelectedTxInfo              = "selectedtxinfo"
	MsgReceiptInfo                 = "receiptinfo"
	MsgLocalParentInfo             = "localparentinfo"
	MsgBlockParams                 = "blockParams"
	MsgWithDrawHash                = "withDrawHash"
	MsgSignerType                  = "signerType"
	MsgParentInfo                  = "parentinfo"
	MsgPendingBlock                = "pendingblock"
	MsgTxsToExecute                = "txsToExecute"
	MsgNonceEuResults              = "nonceEuResults"
	MsgTxsExecuteResults           = "txsExecuteResults"
	MsgTxLocalsUnChecked           = "txLocalsunchecked"
	MsgCheckedTxs                  = "checkedTxs"
	MsgP2pReceived                 = "p2p.received"
	MsgP2pRequest                  = "p2p.request"
	MsgP2pResponse                 = "p2p.response"
	MsgP2pSent                     = "p2p.sent"
	MsgSyncStatusRequest           = "statesync.status.request"
	MsgNonceReady                  = "nonceready"
	MsgMessager                    = "messager"
	MsgOpCommand                   = "opCommand"
	MsgMessagersReaped             = "messagersReaped"
	MsgCommitNonceUrl              = "commitNonceUrl"
	MsgNonceDB                     = "nonceDB"
	MsgNonceCompleted              = "nonceCompleted"
	MsgNoncePrecommit              = "noncePrecommit"
	MsgNonceCommit                 = "nonceCommit"
	MsgFeedBacks                   = "feedbacks"
	MsgSpawnedRelations            = "spawnedRelations"
	MsgSchdState                   = "schdstate"
	MsgSyncStatusResponse          = "statesync.status.response"
	MsgSyncPointResponse           = "statesync.sp.request"
	MsgSyncDataResponse            = "statesync.data.response"
	MsgSyncPointRequest            = "statesync.sp.request"
	MsgSyncDataRequest             = "statesync.data.request"
	MsgExecutingLogs               = "executingLogs"
	MsgConflictInclusive           = "conflictInclusive"
	MsgCheckingTxs                 = "checkingtxs"
	MsgSyncTxRequest               = "txsync.request"
	MsgSyncTxResponse              = "txsync.response"

	MsgBlockCompleted_Success = "success"

	MsgRpcHash        = "rpchash"
	MsgExecGeneration = "execGeneration"
)
